<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5e30cde0-ebf9-42d9-b183-f2c10a5a27cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Neo4j.Driver" Version="6.3.0" />
  </ItemGroup>

</Project>
